### ISSUE TITLE
The result from this tool has some blanks. 

### ISSUE THREAD

**Issue by Kaisei-Iwagami** [microsoft/Microsoft-Defender-for-Identity#10]
Hello, one of my customers tried this script before introducing MDI into his environment. 
He got the following error while he ran the script, then the result has blanks in "AdvancedAuditing" of DCs 

Error Message : 

`Compare-Object : Cannot bind argument to parameter 'DifferenceObject' because it is null.`
 `+...  $isAdvancedAuditingOk = $null -eq (Compare-Object @compareParams)`
   `+CategoryInfo : InvalidData : ( : ) [Compare-Object ], ParametaerBindingValidiationException`
    `+FullyQualifiedErrorId : ParameterArgumentValidiationErrorNullNotAllowed,Microsoft.Powershell.Commands.CompareObjectCommand`

I want to figure out what happened and resolve this problem. 
What can I do for him? Thank you

**Comment by michaelmsonne** [comment]
It seems that the error you're encountering comes from the variable $actual when being "null" (as I see quick), and this is causing issues when you attempt to use it in the Compare-Object cmdlet. This situation happens (based on above statement, not 100% sure) when the script doesn't retrieve any data in the expected format from the remote system.

Some kind of data not get/revived..

Used it here too, not got any issues.

**Comment by michaelmsonne** [comment]
How looks the output from Martin Schvartzman (Microsoft and the guy behind this) script here: https://github.com/martin77s/M365D/blob/7c8814af698c69aff7fd51db00e2125d2555a39d/mdiTroubleshootingPackage.ps1

? :)

**Comment by Kaisei-Iwagami** [comment]
＠michaelmsonne

Thank you for your response!

In my environment, the issue happened as well.
Therefore, I tried the latter script but even though I've been running it for 3 hours, still not finish and nothing I can get from it. 
What kind of output is expected?  
Sorry for bothering you but I really appreciate it if you have any knowledge about that. Thank you.

**Comment by Kaisei-Iwagami** [comment]
> How looks the output from Martin Schvartzman (Microsoft and the guy behind this) script here: https://github.com/martin77s/M365D/blob/7c8814af698c69aff7fd51db00e2125d2555a39d/mdiTroubleshootingPackage.ps1
> 
> @Kaisei-Iwagami ? :)

＠michaelmsonne

Thank you for your response!

In my environment, the issue happened as well.
Therefore, I tried the latter script but even though I've been running it for 3 hours, still not finish and nothing I can get from it.
What kind of output is expected?
Sorry for bothering you but I really appreciate it if you have any knowledge about that. Thank you.

**Comment by Kaisei-Iwagami** [comment]
@michaelmsonne
