### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by hazem1982** [microsoft/Microsoft-Defender-for-Identity#12]
The first time i run the script it worked fine. Later on after 3 days i tried to run it again and i keep getting this error msg 

You cannot call a method on a null-valued expression.
At line:1 char:5
+ if ($PSCmdlet.ShouldProcess($Domain, 'Create MDI related configuratio ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

**Comment by martin77s** [comment]
Please check again with the latest version (1.0.0.1)
