### ISSUE TITLE
Extend script to handle Entra Connect servers

### ISSUE THREAD

**Issue by fulopm** [microsoft/Microsoft-Defender-for-Identity#15]
Since MDI sensor is now available for Entra Connect servers, the script should be extended with the capability to run on Entra Connect servers.

https://techcommunity.microsoft.com/blog/microsoftthreatprotectionblog/protect-and-detect-microsoft-defender-for-identity-expands-to-entra-connect-serv/4226165

**Comment by martin77s** [comment]
@fulopm 
Please see the (new) [DefenderForIdentity](https://www.powershellgallery.com/packages/DefenderForIdentity/) PowerShell module that already includes support for testing / getting / setting the required configuration for Entra connect servers as well.
