### ISSUE TITLE
Problems with MDI Readiness Script

### ISSUE THREAD

**Issue by Jens-Mander-Alumni** [microsoft/Microsoft-Defender-for-Identity#2]
Hi,

I have used the Readiness Script and am basically very enthusiastic about the result.
Unfortunately, I found two challenges.

First, the minimum system requirements are 2 CPU cores + 6GB RAM. For one of my customers, the evaluation for some DCs is marked as "False". Yet the DCs have exactly 6GB of RAM! On the systems themselves I noticed that 6144MB RAM are installed, but "only" 6143MB are available. If I adjust the script (6GB - 1MB), the fields turn green ;-)
If necessary, it makes sense to add a little buffer here in the evaluation?

The second problem is unfortunately more serious. In a larger customer environment I have 3 DCs where Advanced Auditing cannot be evaluated. In the resulting table the field remains empty. During the execution of the script the following error is displayed. Here I could not find out the reason unfortunately, hopefully there is an idea here?

+++++++++++++++++++++++

Get-Content : Cannot find path '\\DCName.contoso.com\C$\Windows\Temp\mdi-GUID.tmp' because it does not exist. At C:\Install\Test-MdiReadiness\Test-MdiReadiness.ps1:77 char:19 +         $return = Get-Content -Path $remoteFile +                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~    + CategoryInfo          : ObjectNotFound: (\\DCName..........tmp:String) [Get-Content], ItemNotFoundException    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetContentCommandRemove-Item : Cannot find path '\\DCName.contoso.com\C$\Windows\Temp\mdi-GUID.tmp' because it does not exist. At C:\Install\Test-MdiReadiness\Test-MdiReadiness.ps1:78 char:9 +         Remove-Item -Path $remoteFile -Force +         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~    + CategoryInfo          : ObjectNotFound: (\\DCName...............tmp:String) [Remove-Item], ItemNotFoundException    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.RemoveItemCommandCompare-Object : Cannot bind argument to parameter 'DifferenceObject' because it is null. At C:\Install\Test-MdiReadiness\Test-MdiReadiness.ps1:383 char:55 +     $isAdvancedAuditingOk = $null -eq (Compare-Object @compareParams) +                                                       ~~~~~~~~~~~~~~    + CategoryInfo          : InvalidData: (:) [Compare-Object], ParameterBindingValidationException    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.CompareObjectCommand

+++++++++++++++++++++++

A view in the JSON-file says:
"AdvancedAuditing":  null,

![image](https://user-images.githubusercontent.com/121574183/209855113-1ff754e9-853a-48a2-90fe-85e1f4447d46.png)

Let's attach some informations from another customer. PowerSettings and Exchange Auditing are not correct evaluated with the script. I think, that is because of the localization of the Active Directory, it was/is (sadly) installed in german. I can see the following error while executing the script:

![image](https://user-images.githubusercontent.com/121574183/210060131-20f73eac-bf8f-4db8-adcd-fb7295ab1620.png)

**Comment by martin77s** [comment]
Fixed
